### ISSUE TITLE
Error Undefined variable: email saat Login

### ISSUE THREAD

**Issue by nafiesl** [revell29/LoginSystem-QRCode#1]
Mas @revell29 saya sudah coba clone project ini.

1. Proses registrasi berhasil, dan dapat foto QR Code
2. Saat coba login dengan email dan password, muncul pesan `Undefined variable: email`.

![selection_190224004](https://user-images.githubusercontent.com/8721551/53300557-e677e880-3883-11e9-9044-5fb0776e36c0.png)

**Comment by revell29** [comment]
sudah saya fix untuk error tersebut :)

**Comment by nafiesl** [comment]
Ok mas @revell29, sudah sukses login setelah pull updatenya. Mantap mas. Saya star dulu.

![selection_190224002](https://user-images.githubusercontent.com/8721551/53301431-d533d980-388d-11e9-9dd2-782f77999d4d.jpg)

**Comment by revell29** [comment]
hehe okee mas. silahkan dikembangkan saja mas siapa tau bisa jadi lebih wah nantinya hehe.
