### ISSUE TITLE
Error Undefined offset: 1 saat login dengan QRCode

### ISSUE THREAD

**Issue by nafiesl** [revell29/LoginSystem-QRCode#2]
Mas @revell29, saya mencoba login dengan QRCode, tetapi mengalami error `Undefined offset: 1`. Setelah di cek di Dev Tool, bagian network, ajax untuk memproses loginnya ada error di LoginController.

![selection_190226006](https://user-images.githubusercontent.com/8721551/53380091-18ce3680-39a7-11e9-9434-2bbb58574250.jpg)

**Comment by revell29** [comment]
oke mas @nafiesl sudah saya update untuk issue tersebut. di sarankan coba untuk register kembali dan scan QR code yang baru. :)

**Comment by nafiesl** [comment]
Wah mantap mas, sudah saya coba dan bisa otomatis login dengan QRCode yang tergenerate.

Terima kasih mas. Keren reponya.

**Comment by revell29** [comment]
hehe oke mas terimakasih sudah bantu report issue nya. mungkin kalo tidak d buat issue tidak akan fix hehe. thanks @nafiesl
